apiVersion: apps/v1
kind: Deployment
metadata:
   name: microapp
spec:
  replicas: 1
  selector:
   matchLables:
      app: microapp
  template:
    metadata: 
      lables:
        app: microapp
    spec: 
      containers:
        name: microapp
        image:  sibixjoy31/micro:latest
        ports:
          containerPort: 8000
      env:
      - name: POSTGRES_DB
        value: micro
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: 1234       