apiVersion: apps/v1
kind: Deployment
metadata:
   name: order
spec:
  replicas: 1
  selector:
   matchLabels:
      app: order
  template:
    metadata: 
      labels:
        app: order
    spec: 
      containers:
      - name: order
        image: sibixjoy31/order:latest
        ports:
        - containerPort: 8001
